### ISSUE TITLE
Check "placeholder" and "name" value to increase accuracy

### ISSUE THREAD

**Issue by eduardabp** [PhilippRecke/Autocomplete-Check#5]
The extension check the labels and `type` attribute, but when a label is missing and value for `type="text"`, it can't verify if an `autocomplete` is needed. Missing labels is a common issue on accessibility, so implementing extra checks, like checking for the `name` or `placeholder` attributes can increase accuracy.

**Comment by PhilippRecke** [comment]
Hi, thank you for your suggestion!
The plugin actually does take multiple parameters into account.

Currently the plugin compares the
- label (text-based)
- placeholder (text-based)
- field type (input/textarea/select)
- input type (text/number/email/date/...)
- name (text-based)
- id (text-based)

The text-based comparisons are all performed on the "byLabel" dictionary, hence probably the confusion, as the keywords you compare against do not differ between the text-based categories.

If detectable, the plugin also determines, wether the form is a login or registration form to take into account for the distinction of "new-password" and "current-password".

Each check is weighed differently, the label having the largest influence on the final prediction.

**Comment by PhilippRecke** [comment]
Let me know, if you have further questions on the whole prediction process. :)
